// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Pr struct {
	ID        uuid.UUID
	Title     string
	AuthorID  uuid.UUID
	TeamID    uuid.UUID
	Status    string
	CreatedAt time.Time
	MergedAt  sql.NullTime
}

type PrReviewer struct {
	PrID       uuid.UUID
	ReviewerID uuid.UUID
}

type Team struct {
	ID       uuid.UUID
	Teamname string
}

type User struct {
	ID       uuid.UUID
	Username string
	IsActive bool
	TeamID   uuid.UUID
}
