// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Pr struct {
	ID        string
	Title     string
	AuthorID  string
	Status    string
	CreatedAt time.Time
	MergedAt  sql.NullTime
}

type PrReviewer struct {
	PrID       string
	ReviewerID string
}

type Team struct {
	ID       string
	Teamname string
}

type User struct {
	ID       string
	Username string
	IsActive bool
	TeamID   string
}
