// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prs.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addReviewer = `-- name: AddReviewer :exec
INSERT INTO pr_reviewers (pr_id, reviewer_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddReviewerParams struct {
	PrID       uuid.UUID
	ReviewerID uuid.UUID
}

func (q *Queries) AddReviewer(ctx context.Context, arg AddReviewerParams) error {
	_, err := q.db.ExecContext(ctx, addReviewer, arg.PrID, arg.ReviewerID)
	return err
}

const createPR = `-- name: CreatePR :exec
INSERT INTO prs (id, title, author_id, team_id, status)
VALUES ($1, $2, $3, $4, 'OPEN')
`

type CreatePRParams struct {
	ID       uuid.UUID
	Title    string
	AuthorID uuid.UUID
	TeamID   uuid.UUID
}

func (q *Queries) CreatePR(ctx context.Context, arg CreatePRParams) error {
	_, err := q.db.ExecContext(ctx, createPR,
		arg.ID,
		arg.Title,
		arg.AuthorID,
		arg.TeamID,
	)
	return err
}

const deleteReviewer = `-- name: DeleteReviewer :exec
DELETE FROM pr_reviewers
WHERE pr_id = $1 AND reviewer_id = $2
`

type DeleteReviewerParams struct {
	PrID       uuid.UUID
	ReviewerID uuid.UUID
}

func (q *Queries) DeleteReviewer(ctx context.Context, arg DeleteReviewerParams) error {
	_, err := q.db.ExecContext(ctx, deleteReviewer, arg.PrID, arg.ReviewerID)
	return err
}

const getActiveTeamMembersExceptAuthor = `-- name: GetActiveTeamMembersExceptAuthor :many
SELECT id
FROM users
WHERE team_id = $1
  AND is_active = TRUE
  AND id <> $2
`

type GetActiveTeamMembersExceptAuthorParams struct {
	TeamID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) GetActiveTeamMembersExceptAuthor(ctx context.Context, arg GetActiveTeamMembersExceptAuthorParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getActiveTeamMembersExceptAuthor, arg.TeamID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPRById = `-- name: GetPRById :one
SELECT id, title, author_id, team_id, status
FROM prs
WHERE id = $1
`

type GetPRByIdRow struct {
	ID       uuid.UUID
	Title    string
	AuthorID uuid.UUID
	TeamID   uuid.UUID
	Status   string
}

func (q *Queries) GetPRById(ctx context.Context, id uuid.UUID) (GetPRByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getPRById, id)
	var i GetPRByIdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.TeamID,
		&i.Status,
	)
	return i, err
}

const getReviewersByPR = `-- name: GetReviewersByPR :many
SELECT reviewer_id
FROM pr_reviewers
WHERE pr_id = $1
`

func (q *Queries) GetReviewersByPR(ctx context.Context, prID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getReviewersByPR, prID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var reviewer_id uuid.UUID
		if err := rows.Scan(&reviewer_id); err != nil {
			return nil, err
		}
		items = append(items, reviewer_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isReviewerAssigned = `-- name: IsReviewerAssigned :one
SELECT COUNT(1) > 0 AS assigned
FROM pr_reviewers
WHERE pr_id = $1 AND reviewer_id = $2
`

type IsReviewerAssignedParams struct {
	PrID       uuid.UUID
	ReviewerID uuid.UUID
}

func (q *Queries) IsReviewerAssigned(ctx context.Context, arg IsReviewerAssignedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isReviewerAssigned, arg.PrID, arg.ReviewerID)
	var assigned bool
	err := row.Scan(&assigned)
	return assigned, err
}

const mergePR = `-- name: MergePR :exec
UPDATE prs
SET status = 'MERGED'
WHERE id = $1
`

func (q *Queries) MergePR(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, mergePR, id)
	return err
}
