// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTeam = `-- name: CreateTeam :exec
INSERT INTO teams (id, teamname)
VALUES ($1, $2)
`

type CreateTeamParams struct {
	ID       uuid.UUID
	Teamname string
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) error {
	_, err := q.db.ExecContext(ctx, createTeam, arg.ID, arg.Teamname)
	return err
}

const getTeamByName = `-- name: GetTeamByName :one
SELECT id, teamname
FROM teams
WHERE teamname = $1
`

func (q *Queries) GetTeamByName(ctx context.Context, teamname string) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByName, teamname)
	var i Team
	err := row.Scan(&i.ID, &i.Teamname)
	return i, err
}

const getUsersByTeam = `-- name: GetUsersByTeam :many
SELECT id, username, is_active, team_id
FROM users
WHERE team_id = $1
ORDER BY username
`

func (q *Queries) GetUsersByTeam(ctx context.Context, teamID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.IsActive,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, username, is_active, team_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET username = EXCLUDED.username,
    is_active = EXCLUDED.is_active,
    team_id = EXCLUDED.team_id
`

type UpsertUserParams struct {
	ID       uuid.UUID
	Username string
	IsActive bool
	TeamID   uuid.UUID
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser,
		arg.ID,
		arg.Username,
		arg.IsActive,
		arg.TeamID,
	)
	return err
}
