// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const getReviewPRs = `-- name: GetReviewPRs :many
SELECT
    prs.id AS pr_id,
    prs.title AS pr_title,
    prs.author_id,
    prs.status
FROM pr_reviewers r
JOIN prs ON prs.id = r.pr_id
WHERE r.reviewer_id = $1
ORDER BY prs.id
`

type GetReviewPRsRow struct {
	PrID     string
	PrTitle  string
	AuthorID string
	Status   string
}

func (q *Queries) GetReviewPRs(ctx context.Context, reviewerID string) ([]GetReviewPRsRow, error) {
	rows, err := q.db.QueryContext(ctx, getReviewPRs, reviewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReviewPRsRow
	for rows.Next() {
		var i GetReviewPRsRow
		if err := rows.Scan(
			&i.PrID,
			&i.PrTitle,
			&i.AuthorID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, is_active, team_id
FROM users
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.IsActive,
		&i.TeamID,
	)
	return i, err
}

const setUserIsActive = `-- name: SetUserIsActive :exec
UPDATE users
SET is_active = $2
WHERE id = $1
`

type SetUserIsActiveParams struct {
	ID       string
	IsActive bool
}

func (q *Queries) SetUserIsActive(ctx context.Context, arg SetUserIsActiveParams) error {
	_, err := q.db.ExecContext(ctx, setUserIsActive, arg.ID, arg.IsActive)
	return err
}
